#!/bin/bash

# convert csv file to html

# Check the command line args
if [[ $# -ne 2 ]]; then
   echo "usage: go3 <cve> <filname for csv file> "  >&2
   echo "example: ./go3 CVE-2002-2443 out/CVE-2002-2443/results.csv"
   exit 1
fi

cve="$1"
infile="$2"
if [ ! -f "$infile" ]; then
   echo Error: file $infile does not exits >&2
   exit 1
fi
base=`echo $infile | sed -e "s/\.csv$//"`
outfile="$base.html"

rm -f $outfile
echo "<table border=1>" >> $outfile
echo "<caption>$cve</caption>" >> $outfile
col="<th>"
while read line; do
    echo "<tr>" >> $outfile
    echo "$col $line" | sed -e "s/,/\n$col/g" >> $outfile
    echo "</tr>" >> $outfile
    col="<td>"
done < $infile
printf "\n</table>\n" >> $outfile
echo "$infile"
echo "$outfile"

echo "Success (go3)"
exit 0
