#! /bin/bash

#
# Given a blob, recursively find new blobs in WoC using ob2b mapping
#

# blob hash for an empty file 
empty_file="e69de29bb2d1d6434b8b29ae775ad8c2e48c5391"
# add the hash for the empty file to the list so that we skip empty files
list=" $empty_file"


#
# Functions
#

#
# ob2b (old blob to blob) mapping.
# input: one or more blobs separated by a newline
#
function ob2b {
    local blobs="$1"
    old_blobs=`printf "$blobs\n" | ~/lookup/getValues -f ob2b 2> /dev/null | cut -d\; -f2 | sort | uniq`
    printf "$old_blobs"
}

#
# ob2b_r
# call ob2b recursively to the end
#
function ob2b_r {
    local blob="$1"
    list+=" $blob"
    obs=$(ob2b "$blob")
    printf "$blob"
    all_blobs+="$blob"
    unique_blobs=''
    for ob in $obs; do
        # check for duplicates, skip if we have already seen this blob
        in=`echo $list | grep $ob`
        if [ "$in" = "" ]; then
            unique_blobs+="$ob"
            unique_blobs+="\n"
        fi
    done
    if [ "$unique_blobs" != "" ]; then
        ob2b_r "$unique_blobs"
    fi
}


#
# Main body of script
#

# Check Command line args
if [[ $# -lt 1 ]]; then
    echo "usage: ob2b_r.sh <blob hash> [<blob hash> ...]"
    exit 1
fi

# for each blob in the input call ob2b to find new blobs
for blobhash in "$@"; do
    obs=$(ob2b "$blobhash")
    if [ "$obs" = "" ]; then
        continue
    fi
    ob2b_r "$obs\n"
done

num_blobs=`printf "$all_blobs" | wc -l`
#echo number of old blobs = $num_blobs >&2
