#! /bin/python

#
# take a project name from WoC and print the URL for the project
#

import sys

def toURL(self):
      '''
      Get the URL for a given project URI
      >>> Project('CS340-19_lectures').toURL()
      'http://github.com/CS340-19/lectures'
      '''
      p_name = self
      found = False
      toUrlMap = {
        "bb": "bitbucket.org", "gl": "gitlab.org",
        "gitlab.com": "gitlab.com",
        "android.googlesource.com": "android.googlesource.com",
        "bioconductor.org": "bioconductor.org",
        "drupal.com": "git.drupal.org", "git.eclipse.org": "git.eclipse.org",
        "git.kernel.org": "git.kernel.org",
        "git.postgresql.org": "git.postgresql.org" ,
        "git.savannah.gnu.org": "git.savannah.gnu.org",
        "git.zx2c4.com": "git.zx2c4.com" ,
        "gitlab.gnome.org": "gitlab.gnome.org",
        "kde.org": "anongit.kde.org",
        "repo.or.cz": "repo.or.cz",
        "salsa.debian.org": "salsa.debian.org",
        "sourceforge.net": "git.code.sf.net/p"}

      for URL in toUrlMap.keys():
        URL_ = URL + "_"
        if p_name.startswith(URL_) and (p_name.count('_') >= 2 or URL == "sourceforge.net"):
          replacement = toUrlMap[URL] + "/"
          p_name = p_name.replace(URL_, replacement)
          found = True
          break

      if not found: 
        p_name = "github.com/" + p_name
 
      p_name = p_name.replace('_', '/', 1)
      return "https://" + p_name  
    

if (len(sys.argv) != 2):
    print "usage: toUrl <projet>"
    sys.exit(1)

print toURL(sys.argv[1])
