#! /bin/bash

#
# file_exists checks to see if a file exists in a repo on github,
# bitbucket, or gitlab.
#

#
# Check the command line args
#
if [ $# -ne 3 ]; then
   echo "usage: file_exists <host> <project> <file path>"
   echo "       supported hosts: github, gitlab, bitbucket"
   echo "           shortcuts: gh, gl, bb"
   echo "       example: file_exists github openssl/openssl SECURITY.md"
   echo "       example: file_exists github ory/examples SECURITY.md"
   echo "       example: file_exists gitlab tortoisegit/tortoisegit SECURITY.md"
   echo "       example: file_exists gitlab gnutls/gnutls SECURITY.md"
   echo "       example: file_exists bitbucket swsc/lookup SECURITY.md"
   exit 1
fi

host=$1
proj=$2
filepath=$3

#
# get the github API auth key(s) from ~/github-auth
#
auth=$(./get_github_authkey)
if [ $? -ne 0 ]; then
    exit 1
fi

#
# Main body of script
#
case $host in
    github|gh)
        empty='[

]'
        url="https://api.github.com/repos/$proj/commits?path=$filepath&per_page=1"
        #echo URL: $url
        while true; do
            response=$(curl -f -s -L -H "Authorization: token $auth" "$url")
            ret=$?
            if [[ $response = *"rate limit exceeded"* ]]; then
                # wait minute then try again 
                echo "Rate limit exceeded in rgitlog, sleeping 60" >&2
                sleep 60
                continue
            elif [[ $ret -ne 0 ]]; then
                echo "No"
                break
            elif [[ "$response" = "$empty" ]]; then
                echo "No"
                break
            else
                echo Yes
                break
            fi
        done
        ;;
    gitlab|gl)
        proj=`echo $proj | sed -e "s@/@%2F@"`
        filepath=`echo $filepath | sed -e "s@/@%2F@"`
        url="https://gitlab.com/api/v4/projects/$proj/repository/commits?path=$filepath&per_page=1"
        #echo URL: $url
        response=$(curl -s "$url")
        if [[ "$response" = "[]" ]]; then
            echo No
        else
            echo Yes
        fi
        ;;
    bitbucket|bb)
        url="https://api.bitbucket.org/2.0/repositories/$proj/commits/?path=$filepath&pagelen=1"
        #echo "URL: $url"
        response=$(curl -s "$url")
        end=`echo "$response" | jq-linux64 -r '{commit: .values[].hash}'`
        if [[ "$end" = "" ]]; then
            echo No
        else
            echo Yes
        fi
        ;;
    *)
        echo "Error: $host not supported, must be one of github, gitlab, or bitbucket"
        exit 1
esac

exit 0

